// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApJOizxlJ4dECSVlaFtRe3A-994fUacUg',
    appId: '1:1011445771363:web:be4fd12939b827328d1c56',
    messagingSenderId: '1011445771363',
    projectId: 'leafy-e18ac',
    authDomain: 'leafy-e18ac.firebaseapp.com',
    databaseURL: 'https://leafy-e18ac-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'leafy-e18ac.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiVQ4T5YEN9cmJHupu11m8Hb_lJD6rp1s',
    appId: '1:1011445771363:android:1a95f15d13794a2f8d1c56',
    messagingSenderId: '1011445771363',
    projectId: 'leafy-e18ac',
    databaseURL: 'https://leafy-e18ac-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'leafy-e18ac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGoBRg6-yyeCnUiZxuu1ySkOtfwWixqpg',
    appId: '1:1011445771363:ios:258671b7fcc0ede88d1c56',
    messagingSenderId: '1011445771363',
    projectId: 'leafy-e18ac',
    databaseURL: 'https://leafy-e18ac-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'leafy-e18ac.firebasestorage.app',
    iosBundleId: 'com.example.iotApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGoBRg6-yyeCnUiZxuu1ySkOtfwWixqpg',
    appId: '1:1011445771363:ios:258671b7fcc0ede88d1c56',
    messagingSenderId: '1011445771363',
    projectId: 'leafy-e18ac',
    databaseURL: 'https://leafy-e18ac-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'leafy-e18ac.firebasestorage.app',
    iosBundleId: 'com.example.iotApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApJOizxlJ4dECSVlaFtRe3A-994fUacUg',
    appId: '1:1011445771363:web:2dd06d6e80bbefac8d1c56',
    messagingSenderId: '1011445771363',
    projectId: 'leafy-e18ac',
    authDomain: 'leafy-e18ac.firebaseapp.com',
    databaseURL: 'https://leafy-e18ac-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'leafy-e18ac.firebasestorage.app',
  );

}